[package]
name = "check"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
getopts = "*"
num_cpus = "*"

[dependencies.scoped_threadpool]
git = "https://github.com/Kimundi/scoped-threadpool-rs"
